# Generated by Django 3.2.16 on 2022-12-28 11:40

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Schedule', max_length=100, unique=True)),
                ('days_off', models.CharField(help_text='Weekdays = 1-7, 1 Being monday, 7 being sunday. Add weekdays off, comma separated Example for Wednesdays &Fridays off: 3,5', max_length=10, validators=[django.core.validators.RegexValidator('^[1-7](,[1-7])*$', message='Wrong format entered!')], verbose_name='Weekly days off')),
                ('special_days_off', models.TextField(help_text='Enter dates, comma separated, no space Example: 2023-01-01,2023-12-31', validators=[django.core.validators.RegexValidator('^(\\s{0,})(\\d{2}\\-\\d{2}\\-\\d{4})(,\\d{2}\\-\\d{2}\\-\\d{4}){1,}(\\s){0,}$', message='Wrong format entered!')], verbose_name='Holidays and other special days off')),
                ('bookable_times', models.TextField(help_text='Format is HOURS:MINUTES, comma separated, no space, Example: 08:15,10:30,11:00', validators=[django.core.validators.RegexValidator('^(?:[01]\\d|2[1-3]):[0-5]\\d(?::[0-5]\\d)?(?:,(?:[01]\\d|2[1-3]):[0-5]\\d(?::[0-5]\\d)?)*$', message='Wrong format entered!')])),
                ('listed', models.BooleanField(default=False, verbose_name='Active schedule')),
            ],
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('customer_length', models.IntegerField(verbose_name='Session lenght(min) with customer')),
                ('real_length', models.IntegerField(verbose_name='Session lenght(min) including prep/post work')),
                ('listed', models.BooleanField(default=False)),
            ],
        ),
    ]
