# Generated by Django 3.2.16 on 2022-12-29 12:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookedsession_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder_cover', max_length=255, verbose_name='image')),
                ('listed', models.BooleanField(default=False)),
                ('slide_nr', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '4'), (4, '4')], max_length=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='real_length',
            field=models.IntegerField(verbose_name='Session lenght(min) including post work'),
        ),
    ]
