# Generated by Django 3.2.16 on 2022-12-29 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_heroimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder_cover', max_length=255, verbose_name='Image (16:9)'),
        ),
    ]
