# Generated by Django 3.2.16 on 2022-12-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_heroimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiontype',
            old_name='customer_length',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='real_length',
        ),
    ]
