# Generated by Django 3.2.16 on 2022-12-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20221230_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduling',
        ),
    ]
