# Generated by Django 3.2.16 on 2022-12-30 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_delete_scheduling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsession',
            name='booked_time',
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Approved')], default=0),
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='time',
            field=models.TimeField(choices=[(0, '8AM'), (1, '9AM'), (2, '10AM'), (3, '11AM'), (4, '12PM'), (5, '13PM'), (6, '14PM'), (7, '15PM'), (8, '16PM')], default='8AM'),
        ),
    ]
