# Generated by Django 3.2.16 on 2022-12-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_bookedsession_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsession',
            name='time',
        ),
    ]
